
update tuCrm_Contract set NoOfPDC=	6	
from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId
where tCrm_Contract.sName=	'Aramed/vipu/037/22'
update tuCrm_Contract set NoOfPDC=	4	
from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId
where sName=	'Aramed/vipu/021/22'
update tuCrm_Contract set NoOfPDC=	4	
from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId
where sName=	'Aramed/vipu/039/21'
update tuCrm_Contract set NoOfPDC=	4	
from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId
where sName=	'Aramed/vipu/028/22'
update tuCrm_Contract set NoOfPDC=	4	
from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId
where sName=	'Aramed/vipu/027/22'
update tuCrm_Contract set NoOfPDC=	4
from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipo/006/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipo/003/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/031/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/032/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/033/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/034/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipk/002/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipb/008/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/040/22'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/bcu/013/20'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipk/008/22'
update tuCrm_Contract set NoOfPDC=	14	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/dqq/0008/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/cco/004/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/ccb/026/21'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipb/025/21'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/cck/002/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/dqu/0063/22'
update tuCrm_Contract set NoOfPDC=	15	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/dqu/0020/22-R1'
update tuCrm_Contract set NoOfPDC=	3	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/dqu/0076/21-R3'
update tuCrm_Contract set NoOfPDC=	12	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/dqu/0102/21-R4'
update tuCrm_Contract set NoOfPDC=	18	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/dqu/0038/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/054/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/054/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/054/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/055/22'
update tuCrm_Contract set NoOfPDC=	8	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/019/22'
update tuCrm_Contract set NoOfPDC=	8	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/028/21'
update tuCrm_Contract set NoOfPDC=	8	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/063/21'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/048/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/057/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Aramed/vipu/056/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/CCK/003/22'
update tuCrm_Contract set NoOfPDC=	12	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'AR/Dr.ASHISH/FW/RL1C2603I'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCU/007/22'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCB/005/22'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCB/002/22'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCB/001/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/064/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIP/012/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/017/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/043/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'AR/VIPB/GermanMedicalCenter/Synchro 3.4/RG7B132Q/1720005238'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'AR/VIPB/GermanMedicalCenter/Synchro 3.4/RG8B363Q/1820008653'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'AR/VIPB/GermanMedicalCenter/Synchro3.4/RG8B362Q/1820008652'
update tuCrm_Contract set NoOfPDC=	8	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'AR/VIPU/Hanover/RG9B101Q/21'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/063/22-R1'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/042/22-RG1C031Q'
update tuCrm_Contract set NoOfPDC=	8	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/049/22-RG0C121Q'
update tuCrm_Contract set NoOfPDC=	1	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/066/22-RG0C272Q'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/065/22-RG9B092Q/1920002025'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/007/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/009/22'
update tuCrm_Contract set NoOfPDC=	8	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/041/22-RG8B371Q'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/065/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAAMED/VIPB/014/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/014/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/014/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/016/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/011/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/019/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/017/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/CCO/01/22 - QS7B3401'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/CCO/01/22 - UM7B1501B'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/CCO/01/22 -TU9B275C'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/CCO/01/22 - QS9B4501'
update tuCrm_Contract set NoOfPDC=	8	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/071/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPO/007/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/018/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/NW/PUREDERMATOLOGY/RL220106/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIBK/016/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/010/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/016/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/016/22'
update tuCrm_Contract set NoOfPDC=	3	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPQ/016/22'
update tuCrm_Contract set NoOfPDC=	3	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPQ/015/22'
update tuCrm_Contract set NoOfPDC=	3	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPQ/013/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/017/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/011/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/076/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/076/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/010/22'
update tuCrm_Contract set NoOfPDC=	8	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/072/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'HeathLine day care surgery L.L.C'
update tuCrm_Contract set NoOfPDC=	5	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/070/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/017/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/059/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/059/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/075/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/075/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/021/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/074/22'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/015/22'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/015/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/086/22'
update tuCrm_Contract set NoOfPDC=	3	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPQ/011/22'
update tuCrm_Contract set NoOfPDC=	3	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPQ/012/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'Advance Cure Diagnostic Center L.L.C'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/084/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/081/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/091/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/089/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/092/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/090/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/087/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/088/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/012/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/024/22-QM6B272A'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/024-QM9B497A'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/021/22-RG9B373Q'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/021/22-RG9B373Q'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/052/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/079/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/021/22-RG9B373Q'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCU/033/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/025/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/025/22-RG9B465Q'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/025/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/025/22-RG9B465Q'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCU/040/22'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCU/038/22'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCU/038/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/092/22-Rg1c053q'
update tuCrm_Contract set NoOfPDC=	8	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/061/22'
update tuCrm_Contract set NoOfPDC=	8	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/077/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/092/22-RG1C053Q'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/099/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/098/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/100/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/083/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/026/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/030/22-RG0C161Q'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/030/22-R1'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/001/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/001/23-RG1C034Q'
update tuCrm_Contract set NoOfPDC=	6	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/003/23'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCU/041/22'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/005/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/016/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/002/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/001/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/010/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/011/23'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCU/005/23'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCU/004/23'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCU/007/23'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCU/007/23 _UM6B4103B'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPQ/014/22 - RG0C261Q'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/002/23'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAME/VIPU/001/23'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCU/002/23'
update tuCrm_Contract set NoOfPDC=	3	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCU/009/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/024/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPQ/001/23'
update tuCrm_Contract set NoOfPDC=	8	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPO/001/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/008/23'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/015/23'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/028/23'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/014/23'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/013/23'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/012/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/003/23'
update tuCrm_Contract set NoOfPDC=	8	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPO/006/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/CCK/001/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/035/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/036/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPO/004/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPQ/007/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPQ/016/22-RG9B473Q'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPQ/015/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/049/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/021/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/030/23'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/040/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/051/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/037/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPK/012/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPB/005/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/063/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'AR/EveMedicalCenter/UAE/Onda/TU1C154CB/22'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=   '	ARAMED/VIPU/058/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/059/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/060/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/061/23'
update tuCrm_Contract set NoOfPDC=	4	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/062/23'
update tuCrm_Contract set NoOfPDC=	10	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/VIPU/052/23'
update tuCrm_Contract set NoOfPDC=	2	from tuCrm_Contract
join tCrm_Contract on tCrm_Contract.iTransId=tuCrm_Contract.iTransId where sName=	'ARAMED/BCU/019/23'


